timezone: Africa/Nairobi

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            HS - Develop & Design
tagline:          Develop + Design
description:      Develop + Design web apps, mobile apps & graphic design (logos, illustrations, icons)
defaultimg:       default_img.png
# highlighter:      pygments
markdown:         redcarpet
pagination:       1
paginate_path:    "blog/pg:num/"
url:              http://habu-kagumba.github.io/
logo: 			  logo.svg
baseurl:          /
author:
  name:           Herbert Kagumba
  url:            http://habu-kagumba.github.io/
  email:          hs@hs-dev-design.com

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
exclude: [".sass-cache", "assets/js/vendor", "assets/img", "assets/css/vendor", "bower_components", "node_modules"]
owner:
  name: Herbert Kagumba
  job: Front-End & Back-End Development
  desc: Front-End & Back-End Developer extraordinaire
  po: 733-00515, Buruburu, Kenya
  city: Nairobi
  pocode: 00515
  country: Kenya
  email: herbertkagumba@gmail.com
  tel: 254727114286
  twitter: HabuKagumba
  github: Habu-Kagumba
  facebook_id: 1374429249534174
  google:
    plus: herbertkagumba
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  avatar: me.svg
disqus_shortname: hsdevdesign

#gems
gems:
  - jekyll-sitemap
